api_to_test: local_api 

apis:
  openai:
    name: OpenAI
    endpoint: https://api.openai.com/v1/chat/completions
    auth_required: true
    api_key_env_var: OPENAI_API_KEY
    headers:
      Content-Type: application/json
      Authorization: "Bearer {api_key}"
    request_body:
      model: gpt-3.5-turbo
      messages:
        - role: user
          content: "{question}"
      temperature: 0.7
    response_path: choices[0].message.content

  anthropic:
    name: Anthropic
    endpoint: https://api.anthropic.com/v1/complete
    auth_required: true
    api_key_env_var: ANTHROPIC_API_KEY
    headers:
      Content-Type: application/json
      X-API-Key: "{api_key}"
    request_body:
      model: claude-v1
      prompt: "\n\nHuman: {question}\n\nAssistant:"
      max_tokens_to_sample: 512
      temperature: 0.7
    response_path: completion

  custom_llm:
    name: CustomLLM
    endpoint: https://your-custom-llm.com/api/generate
    auth_required: true
    api_key_env_var: CUSTOM_LLM_API_KEY
    headers:
      Content-Type: application/json
      Authorization: "Bearer {api_key}"
    request_body:
      question: "{question}"
    response_path: answer

  local_api:
    name: LocalAPI
    endpoint: http://127.0.0.1:8025/answer
    auth_required: false  # Authentication not required
    headers:
      accept: application/json
      Content-Type: application/json
    request_body:
      question: "{question}"
    response_path: answer
